# Generated by Django 3.0.3 on 2020-03-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='caption_four',
            field=models.CharField(default='caption', max_length=100),
        ),
    ]
